refactor: the name of an example now describes what is tested in it
neohelden/Flutter-AdaptiveCards pull request #77
Opened 2021-08-04 07:24 UTC by Curvel

In addition, all JSON files now have the file type ".json".

2021-08-04 08:33 UTC, daniel-vera-g requested changes

2021-08-04 08:33 UTC, daniel-vera-g commented on test/utils/test_utils.dart
> +  var hostConfigFile = File('test/host_configs/$hostConfigPath.json');
```suggestion
  var hostConfigFile = File('test/host_configs/$hostConfigPath');
```

I could not find an error in the examples and am not sure where it is used there, but at first sight it seems wrong.

It get's called on line 10 and in the `sample_some_tests.dart` on line 17 with the `.json` extension already set.

2021-08-04 13:12 UTC, Curvel commented on test/utils/test_utils.dart
> +  var hostConfigFile = File('test/host_configs/$hostConfigPath.json');
good catch, changed it

2021-08-05 06:58 UTC, daniel-vera-g approved these changes
LGTM

2021-08-05 06:59 UTC, merged